from __future__ import annotations

from typing import Protocol

from deepem.protocol import CaseRecord, ChatMessage, Conversation, Event, Part, Run, StateSnapshot, Task, ToolCall


class TaskRepo(Protocol):
    def create(self, task: Task) -> Task: ...
    def get(self, task_id: str) -> Task: ...
    def save(self, task: Task) -> Task: ...
    def list_recent(self, limit: int | None = None) -> list[Task]: ...


class ConversationRepo(Protocol):
    def create(self, conversation: Conversation) -> Conversation: ...
    def get(self, conversation_id: str) -> Conversation: ...
    def get_by_task(self, task_id: str) -> Conversation: ...
    def list_by_task(self, task_id: str) -> list[Conversation]: ...
    def save(self, conversation: Conversation) -> Conversation: ...
    def delete(self, conversation_id: str) -> None: ...


class ChatMessageRepo(Protocol):
    def append(self, message: ChatMessage) -> ChatMessage: ...
    def list_by_conversation(self, conversation_id: str, limit: int | None = None) -> list[ChatMessage]: ...
    def delete_by_conversation(self, conversation_id: str) -> None: ...


class EventRepo(Protocol):
    def append(self, event: Event) -> Event: ...
    def get(self, event_id: str) -> Event: ...
    def next_seq(self, task_id: str) -> int: ...
    def list_by_task(self, task_id: str, limit: int | None = None) -> list[Event]: ...
    def list_after(self, task_id: str, seq: int, limit: int | None = None) -> list[Event]: ...
    def exists_by_idempotency_key(self, task_id: str, key: str) -> bool: ...


class RunRepo(Protocol):
    def create(self, run: Run) -> Run: ...
    def get(self, run_id: str) -> Run: ...
    def save(self, run: Run) -> Run: ...
    def list_by_task(self, task_id: str, limit: int | None = None) -> list[Run]: ...


class PartRepo(Protocol):
    def append(self, part: Part) -> Part: ...
    def list_by_run(self, run_id: str) -> list[Part]: ...
    def list_recent_by_task(self, task_id: str, limit: int | None = None) -> list[Part]: ...


class ToolCallRepo(Protocol):
    def create(self, tool_call: ToolCall) -> ToolCall: ...
    def save(self, tool_call: ToolCall) -> ToolCall: ...
    def list_by_run(self, run_id: str) -> list[ToolCall]: ...


class StateRepo(Protocol):
    def create(self, snapshot: StateSnapshot) -> StateSnapshot: ...
    def get(self, task_id: str) -> StateSnapshot: ...
    def save(self, snapshot: StateSnapshot) -> StateSnapshot: ...


class CaseRepo(Protocol):
    def get_by_signal(self, task_id: str, signal_id: str) -> CaseRecord | None: ...
    def save(self, case: CaseRecord) -> CaseRecord: ...
    def list_by_task(self, task_id: str) -> list[CaseRecord]: ...


class KnowledgeBase(Protocol):
    def get_place_baseline(self, place_id: str) -> list[str]: ...
    def set_place_baseline(self, place_id: str, fingerprints: list[str]) -> list[str]: ...
    def describe_place(self, place_id: str) -> dict[str, object]: ...
    def lookup_signal(self, fingerprint: str) -> dict[str, object] | None: ...
    def search(self, query: str, place_id: str | None = None) -> dict[str, object]: ...
